kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/fanux/fist-ui

steps:
- name: build-font
  image: fanux/vue:latest
  commands:
     - npm install
     - npm run build

#- name: publish-font
#  image: plugins/docker
#  settings:
#    repo: lameleg/fist-ui
#    tags: ${DRONE_TAG=latest}
#    username:
#      from_secret: docker-hub-user
#    dockerfile: docker/Dockerfile
#    password:
#      from_secret: docker-hub-pass

- name: deploy-font
  image: cuisongliu/drone-kube
  settings:
    server:
      from_secret: k8s-server
    ca:
      from_secret: k8s-ca
    admin:
      from_secret: k8s-admin
    admin_key:
      from_secret: k8s-admin-key
  commands:
#    - mkdir ~/.kube
#    - cp deploy/config ~/.kube/config
#    - env
    - drone-kube config >> config
    - echo "debug....."
    - cat config
    - echo "/root/.kube/config"
    - cat /root/.kube/config
    - kubectl delete -f deploy/deploy.yaml || true
    - sleep 15
    - kubectl create -f deploy/deploy.yaml || true
