kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/fanux/fist-ui

steps:
- name: build-font
  image: fanux/vue:latest
  commands:
     - npm install
     - npm run build

- name: publish-font
  image: plugins/docker
  settings:
    repo: lameleg/fist-ui
    tags: ${DRONE_TAG=latest}
    username:
      from_secret: docker-hub-user
    dockerfile: docker/Dockerfile
    password:
      from_secret: docker-hub-pass
  commands:
    - env

#- name: deploy-font
#  image: lachlanevenson/k8s-kubectl
#  settings:
#
#  commands:
#    - mkdir ~/.kube
#    - cp deploy/config ~/.kube/config
#    - kubectl delete -f deploy/deploy.yaml || true
#    - sleep 15
#    - kubectl create -f deploy/deploy.yaml || true
